Repository codeit-part4/sb01-mople-team2, pull requests merged in 2025-06, with the labels that each got.

#13 Feature: 팔로우, DM 관련 엔티티, 레포, dto 추가
  build.gradle
  src/main/java/com/sprint/mople/domain/dm/dto/ChatRoomCreateRequest.java
  src/main/java/com/sprint/mople/domain/dm/dto/MessageResponse.java
  src/main/java/com/sprint/mople/domain/dm/entity/ChatRoom.java
  src/main/java/com/sprint/mople/domain/dm/entity/Message.java
  src/main/java/com/sprint/mople/domain/dm/repository/ChatRoomRepository.java
  src/main/java/com/sprint/mople/domain/dm/repository/MessageRepository.java
  src/main/java/com/sprint/mople/domain/follow/dto/FollowResponse.java
  src/main/java/com/sprint/mople/domain/follow/entity/Follow.java
  src/main/java/com/sprint/mople/domain/follow/repository/FollowRepository.java
Labels: feature

#14 Feature: 컨텐츠 및 watchSession 엔티티/레포지토리 생성
  src/main/java/com/sprint/mople/domain/content/entity/Content.java
  src/main/java/com/sprint/mople/domain/content/repository/ContentRepository.java
  src/main/java/com/sprint/mople/domain/watchsession/entity/WatchComment.java
  src/main/java/com/sprint/mople/domain/watchsession/entity/WatchSession.java
  src/main/java/com/sprint/mople/domain/watchsession/entity/WatchSessionParticipant.java
  src/main/java/com/sprint/mople/domain/watchsession/repository/WatchCommentRepository.java
  src/main/java/com/sprint/mople/domain/watchsession/repository/WatchSessionParticipantRepository.java
  src/main/java/com/sprint/mople/domain/watchsession/repository/WatchSessionRepository.java
Labels: feature

#20 Feat/7: 리뷰 관련 CRUD 생성
  src/main/java/com/sprint/mople/domain/content/repository/ContentRepository.java
  src/main/java/com/sprint/mople/domain/dm/entity/ChatRoom.java
  src/main/java/com/sprint/mople/domain/dm/entity/Message.java
  src/main/java/com/sprint/mople/domain/review/controller/ReviewApi.java
  src/main/java/com/sprint/mople/domain/review/controller/ReviewController.java
  src/main/java/com/sprint/mople/domain/review/dto/ContentRatingSummaryDto.java
  src/main/java/com/sprint/mople/domain/review/dto/ReviewCreateRequest.java
  src/main/java/com/sprint/mople/domain/review/dto/ReviewResponse.java
  src/main/java/com/sprint/mople/domain/review/dto/ReviewUpdateRequest.java
  src/main/java/com/sprint/mople/domain/review/entity/Review.java
  src/main/java/com/sprint/mople/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/sprint/mople/domain/review/repository/ReviewRepository.java
  src/main/java/com/sprint/mople/domain/review/service/ReviewService.java
  src/main/java/com/sprint/mople/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sprint/mople/domain/user/repository/UserRepository.java
  src/main/java/com/sprint/mople/global/exception/ErrorCode.java
  src/main/java/com/sprint/mople/global/exception/ErrorResponse.java
  src/main/java/com/sprint/mople/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mople/global/exception/MopleException.java
  src/main/resources/application.yaml
Labels: fix, feature

#22 Feature/15: 팔로우, 언팔로우 API 구현 및 jacoco 추가
  .github/workflows/coverage.yml
  README.md
  build.gradle
  gradlew
  src/main/java/com/sprint/mople/domain/follow/controller/FollowController.java
  src/main/java/com/sprint/mople/domain/follow/mapper/FollowMapper.java
  src/main/java/com/sprint/mople/domain/follow/repository/FollowRepository.java
  src/main/java/com/sprint/mople/domain/follow/service/FollowService.java
  src/main/java/com/sprint/mople/domain/follow/service/FollowServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/sprint/mople/follow/FollowTest.java
Labels: feature

#21 Ci/19 : 테스트와 빌드 분리 및 DDL validate하게 변경
  .github/workflows/pull-request.yaml
  src/main/resources/schema.sql
  src/test/resources/application-test.yml
Labels: DDL, ci

#29 Feat: DM 관련 기능 구현
  .github/workflows/coverage.yml
  build.gradle
  src/main/java/com/sprint/mople/domain/dm/controller/ChatRoomController.java
  src/main/java/com/sprint/mople/domain/dm/controller/MessageController.java
  src/main/java/com/sprint/mople/domain/dm/dto/ChatRoomCreateRequest.java
  src/main/java/com/sprint/mople/domain/dm/dto/ChatRoomResponse.java
  src/main/java/com/sprint/mople/domain/dm/dto/MessageCreateRequest.java
  src/main/java/com/sprint/mople/domain/dm/dto/MessageResponse.java
  src/main/java/com/sprint/mople/domain/dm/entity/ChatRoom.java
  src/main/java/com/sprint/mople/domain/dm/entity/ChatRoomUser.java
  src/main/java/com/sprint/mople/domain/dm/entity/ChatRoomUserId.java
  src/main/java/com/sprint/mople/domain/dm/entity/Message.java
  src/main/java/com/sprint/mople/domain/dm/exception/ChatRoomNotFoundException.java
  src/main/java/com/sprint/mople/domain/dm/mapper/ChatRoomMapper.java
  src/main/java/com/sprint/mople/domain/dm/mapper/MessageMapper.java
  src/main/java/com/sprint/mople/domain/dm/repository/ChatRoomUserRepository.java
  src/main/java/com/sprint/mople/domain/dm/repository/MessageRepository.java
  src/main/java/com/sprint/mople/domain/dm/service/ChatRoomService.java
  src/main/java/com/sprint/mople/domain/dm/service/ChatRoomServiceImpl.java
  src/main/java/com/sprint/mople/domain/dm/service/MessageService.java
  src/main/java/com/sprint/mople/domain/dm/service/MessageServiceImpl.java
  src/main/java/com/sprint/mople/domain/follow/controller/FollowController.java
  src/main/java/com/sprint/mople/domain/follow/dto/FollowResponse.java
  src/main/java/com/sprint/mople/domain/follow/exception/FollowNotFoundException.java
  src/main/java/com/sprint/mople/domain/follow/service/FollowServiceImpl.java
  src/main/java/com/sprint/mople/global/config/WebsocketConfig.java
  src/main/java/com/sprint/mople/global/exception/ErrorCode.java
  src/main/java/com/sprint/mople/global/jwt/JwtProvider.java
  src/main/java/com/sprint/mople/global/jwt/JwtTokenExtractor.java
  src/main/resources/schema.sql
  src/test/java/com/sprint/mople/domain/dm/service/ChatRoomServiceImplTest.java
  src/test/java/com/sprint/mople/domain/dm/service/MessageServiceImplTest.java
  src/test/java/com/sprint/mople/follow/FollowServiceImplTest.java
  src/test/resources/application-test.yml
Labels: feature
